# Generated by Django 5.0.7 on 2024-08-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='createdDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
