# Generated by Django 5.0.7 on 2024-08-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docs', '0002_alter_folder_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='createdDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
