# Generated by Django 5.0.7 on 2024-09-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Docs', '0004_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
