# Generated by Django 5.0.7 on 2024-08-03 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DCI', '0001_initial'),
        ('Docs', '0001_initial'),
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSubmissionAgencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DSATName', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSubmissionAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('contactPersons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.contactperson')),
                ('agencytype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Submissions.documentsubmissionagencytype')),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisionNo', models.IntegerField(blank=True, null=True)),
                ('whyRevision', models.TextField(blank=True, null=True)),
                ('checkingDate', models.DateField(blank=True, null=True)),
                ('printingDate', models.DateField(blank=True, null=True)),
                ('submissionDate', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('earlierSubmissionReference', models.CharField(blank=True, max_length=30, null=True)),
                ('commentIfAny', models.TextField(blank=True, null=True)),
                ('commentDocument', models.FileField(blank=True, null=True, upload_to='')),
                ('commentReply', models.TextField(blank=True, null=True)),
                ('replyDocument', models.FileField(blank=True, null=True, upload_to='')),
                ('approved', models.BooleanField(blank=True, default=False, null=True)),
                ('approvalDate', models.DateField(blank=True, null=True)),
                ('checkedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.staff')),
                ('dciItems', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DCI.dciitem')),
                ('documents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Docs.document')),
                ('printedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='printingStaff', to='Project.staff')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
                ('submittedTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Submissions.documentsubmissionagencytype')),
            ],
        ),
    ]
