# Generated by Django 5.0.7 on 2024-09-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Submissions', '0002_alter_submissions_submittedto'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Name'),
        ),
    ]
