# Generated by Django 5.0.7 on 2024-09-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Submissions', '0003_submissions_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
    ]
