# Generated by Django 5.0.7 on 2024-09-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCI', '0008_dciitem_dci'),
        ('Submissions', '0004_alter_submissions_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissions',
            name='dciItems',
        ),
        migrations.AddField(
            model_name='submissions',
            name='dciItems',
            field=models.ManyToManyField(blank=True, null=True, to='DCI.dciitem'),
        ),
    ]
