# Generated by Django 5.0.7 on 2024-10-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCI', '0008_dciitem_dci'),
        ('Submissions', '0005_remove_submissions_dciitems_submissions_dciitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='dciItems',
            field=models.ManyToManyField(to='DCI.dciitem'),
        ),
    ]
