# Generated by Django 5.0.7 on 2024-09-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_alter_tasks_taskname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='assignmentDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
