# Generated by Django 5.0.7 on 2024-09-11 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_alter_hinderances_dateofoccurrence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskactivities',
            name='completionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskactivities',
            name='entryDoneBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entryDone', to=settings.AUTH_USER_MODEL),
        ),
    ]
