# Generated by Django 5.0.7 on 2024-09-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0006_taskactivities_completiondate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hinderancefollowup',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
