# Generated by Django 5.0.7 on 2024-09-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0007_alter_hinderancefollowup_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskactivities',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
