# Generated by Django 5.0.7 on 2024-09-27 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCI', '0008_dciitem_dci'),
        ('Tasks', '0009_tasks_dciitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='dciItem',
        ),
        migrations.AddField(
            model_name='tasks',
            name='dciItem',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DCI.dciitem'),
        ),
    ]
