# Generated by Django 5.0.7 on 2024-09-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCI', '0008_dciitem_dci'),
        ('Tasks', '0010_remove_tasks_dciitem_tasks_dciitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='dciItem',
        ),
        migrations.AddField(
            model_name='tasks',
            name='dciItem',
            field=models.ManyToManyField(blank=True, null=True, to='DCI.dciitem'),
        ),
    ]
