# Generated by Django 5.0.7 on 2024-10-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCI', '0008_dciitem_dci'),
        ('Tasks', '0011_remove_tasks_dciitem_tasks_dciitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='dciItem',
            field=models.ManyToManyField(to='DCI.dciitem'),
        ),
    ]
