# Generated by Django 5.0.7 on 2024-11-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCI', '0008_dciitem_dci'),
        ('Tasks', '0012_alter_tasks_dciitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='dciItem',
            field=models.ManyToManyField(related_name='dci_items', to='DCI.dciitem'),
        ),
    ]
