# Generated by Django 5.0.7 on 2024-08-03 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=50)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('agency', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=30, null=True)),
                ('sourceDescription', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScopeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectorName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile1', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile2', models.CharField(blank=True, max_length=10, null=True)),
                ('landline', models.CharField(blank=True, max_length=15, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.client')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissionDate', models.DateField(blank=True, null=True)),
                ('proposalCost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('accepted', models.BooleanField(blank=True, default=False, null=True)),
                ('acceptedDate', models.DateField(blank=True, null=True)),
                ('workOrderNo', models.CharField(blank=True, max_length=15, null=True)),
                ('workOrderDate', models.DateField(blank=True, null=True)),
                ('workOrderCost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('projectLead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.projectlead')),
                ('submittedTo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.client')),
            ],
        ),
        migrations.AddField(
            model_name='projectlead',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.sector'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathersName', models.CharField(blank=True, max_length=30, null=True)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('addressPresent', models.TextField(blank=True, null=True)),
                ('addressHome', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile1', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile2', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(blank=True, max_length=30, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('agency', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('dateOfCommencement', models.DateField(blank=True, null=True)),
                ('lastDateOfDelivery', models.DateField(blank=True, null=True)),
                ('projectProposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.projectproposal')),
                ('scopeItems', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.scopeitem')),
                ('sector', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.sector')),
                ('incharge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incharge_projects', to='Project.staff')),
            ],
        ),
    ]
