# Generated by Django 5.0.7 on 2024-09-07 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCI', '0007_remove_dci_project'),
        ('Project', '0004_scopegroup_scopeitem_scopegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproposal',
            name='docControlIndex',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DCI.dci'),
        ),
    ]
