# Generated by Django 5.0.7 on 2024-09-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_projectproposal_doccontrolindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='File'),
        ),
        migrations.AddField(
            model_name='project',
            name='workOrderDate',
            field=models.DateField(blank=True, null=True, verbose_name='Work Order Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='workOrderNo',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Work Order Number'),
        ),
    ]
