# Generated by Django 5.0.7 on 2024-09-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_project_file_project_workorderdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='scopeItems',
        ),
    ]
