# Generated by Django 5.0.7 on 2024-09-10 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_remove_project_scopeitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlead',
            name='scopeItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.scopeitem'),
        ),
    ]
