# Generated by Django 5.0.7 on 2024-09-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_projectlead_scopeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlead',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
