# Generated by Django 5.0.7 on 2024-09-23 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0009_projectlead_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Project.sector'),
        ),
        migrations.AlterField(
            model_name='projectlead',
            name='source',
            field=models.CharField(max_length=30),
        ),
    ]
