# Generated by Django 5.0.7 on 2024-09-27 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCI', '0008_dciitem_dci'),
        ('Project', '0011_project_finaldci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finalDCI',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DCI.dci'),
        ),
    ]
