# Generated by Django 5.0.7 on 2024-10-05 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCI', '0008_dciitem_dci'),
        ('Project', '0012_alter_project_finaldci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectproposal',
            name='docControlIndex',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DCI.dci'),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='submittedTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.client'),
        ),
    ]
