# Generated by Django 5.0.7 on 2024-10-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0014_alter_projectproposal_projectlead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlead',
            name='approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
