# Generated by Django 5.0.7 on 2024-11-16 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0016_parent_child'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
