# Generated by Django 5.0.7 on 2024-08-03 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.project')),
            ],
        ),
        migrations.CreateModel(
            name='DCIGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('groupCode', models.CharField(blank=True, max_length=15, null=True)),
                ('dci', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DCI.dci')),
            ],
        ),
        migrations.CreateModel(
            name='DCIItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sNo', models.IntegerField()),
                ('itemCode', models.CharField(blank=True, max_length=15, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('likelySubmissionDate', models.DateField(blank=True, null=True)),
                ('associatedCost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('dciGroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DCI.dcigroup')),
            ],
        ),
    ]
