# Generated by Django 5.0.7 on 2024-08-10 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCI', '0002_dciitem_documentno_dciitem_weightage'),
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dci',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Project.project'),
        ),
    ]
