# Generated by Django 5.0.7 on 2024-08-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCI', '0003_alter_dci_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dciitem',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dciitem',
            name='sNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
