# Generated by Django 5.0.7 on 2024-09-03 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCI', '0004_alter_dciitem_name_alter_dciitem_sno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dciitem',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dciitem',
            name='createdDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
