# Generated by Django 5.0.7 on 2024-09-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCI', '0005_dciitem_createdby_dciitem_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dci',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
