# Generated by Django 5.0.7 on 2024-09-07 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DCI', '0006_dci_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dci',
            name='project',
        ),
    ]
