# Generated by Django 5.0.7 on 2024-09-27 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCI', '0007_remove_dci_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='dciitem',
            name='dci',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DCI.dci'),
        ),
    ]
