# Generated by Django 5.0.7 on 2024-11-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCI', '0009_dciitem_completed_dciitem_dateofcompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dciitem',
            name='dateOfCompletion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
